backend:
  name: github
  repo: rofor8/urbanbiome-website
  branch: main
  base_url: https://urbanbiome.co.uk
  auth_endpoint: /api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "sections"
    label: "Page Sections"
    folder: "src/content/sections"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Order", name: "order", widget: "number", value_type: "int"}
      - {label: "Navigation Title (Optional)", name: "navTitle", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Configuration"
        name: "site"
        file: "src/content/settings/site.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - label: "Color Scheme"
            name: "colors"
            widget: "object"
            fields:
              - {label: "Primary Color", name: "primary", widget: "string", hint: "Hex color code (e.g., #2c5f2d)"}
              - {label: "Secondary Color", name: "secondary", widget: "string", hint: "Hex color code"}
              - {label: "Accent Color", name: "accent", widget: "string", hint: "Hex color code"}
              - {label: "Background Color", name: "background", widget: "string", hint: "Hex color code"}
              - {label: "Text Color", name: "text", widget: "string", hint: "Hex color code"}
